### ISSUE TITLE
Right CLI way

### ISSUE THREAD

**Issue by goalia** [zapier/zapier-platform-example-app-search#3]
When I want to install the template with the following cli : 
zapier init --template=search
I've got an error : 
Errors running command `zapier init --template=search`:
!!!   Missing required positional argument 1/path
For more information, run `zapier help init`.

I've fixed the error by adding a . before -- like this :
zapier init . --template=search
Maybe you need to rewrite the readme file 
Regards

**Comment by xavdid** [comment]
Hey there! What you've reported sounds like correct behavior. The command is `zapier init <PATH>`, and you can supply a template. Without a path, an error is thrown (correctly). 

Is there something we could be more clear on?

**Comment by FokkeZB** [comment]
@Goal54 I've updated the readme to include `<path>`. Thanks for spotting that!

**Comment by FokkeZB** [comment]
@xavdid I see we have the same bug in other/all examples:
https://github.com/zapier/zapier-platform-example-app-files

Do we have a script we can to fix all of them?

**Comment by xavdid** [comment]
Not really :( I can work on something though, that's an issue that's come up a lot

**Comment by goalia** [comment]
Thank's, yes I see that in the others examples :/

**Comment by FokkeZB** [comment]
@xavdid Let me know if you will, otherwise I'll just fix this in all repos

**Comment by xavdid** [comment]
@FokkeZB I looked at tools such as [repoman](https://github.com/basti1302/repoman) and [mr](https://myrepos.branchable.com/), but they both seem to use github basic auth, which I don't believe we're supposed to give out. I think I can use the former to make some changes in each of the readmes, and then commit/push manually. I'll double check with security but hopefully this isn't to bad. if that doesn't shake out, i'll let you know!
